[package]
name = "ethertia"
version = "0.1.0"
edition = "2021"

[dependencies]

bevy = "0.12"

bevy_atmosphere = "0.8"

bevy_egui = "0.23"

bevy-inspector-egui = "0.21"
bevy_editor_pls = "0.6"

native-dialog = "0.6.4"
sysinfo = "0.29.10"
memory-stats = "1.1.0"

log = "0.4.20"
env_logger = "0.10.0"
chrono = "0.4.31"
anyhow = "1.0.75"  # error handling


[workspace]
resolver = "2" # Important! wgpu/bevy needs this!


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3