name: Android

on:
  create:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      APP_NAME: ethertia
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: |
          rustup target add aarch64-linux-android
          cargo install --force cargo-apk

      - name: Build for Android
        run: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --profile android-debug --no-default-features

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-artifacts
          path: |
            ./target/android-debug/${APP_NAME}.apk